## Preparing Library and Data

In [1]:
# import library
import pandas as pd
import numpy as np
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/dsmbc-2025-kaggle-war-bank-marketing-campaign-pre/sample_submission.csv
/kaggle/input/dsmbc-2025-kaggle-war-bank-marketing-campaign-pre/train.csv
/kaggle/input/dsmbc-2025-kaggle-war-bank-marketing-campaign-pre/test.csv
/kaggle/input/pm-96835262-at-10-30-2025-18-34-27/__script__.py
/kaggle/input/pm-96835262-at-10-30-2025-18-34-27/__results__.html
/kaggle/input/pm-96835262-at-10-30-2025-18-34-27/joblib-1.5.2-py3-none-any.whl
/kaggle/input/pm-96835262-at-10-30-2025-18-34-27/input_requirements.txt
/kaggle/input/pm-96835262-at-10-30-2025-18-34-27/scipy-1.16.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
/kaggle/input/pm-96835262-at-10-30-2025-18-34-27/threadpoolctl-3.6.0-py3-none-any.whl
/kaggle/input/pm-96835262-at-10-30-2025-18-34-27/scikit_learn-1.7.2-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
/kaggle/input/pm-96835262-at-10-30-2025-18-34-27/__script__.ipynb
/kaggle/input/pm-96835262-at-10-30-2025-18-34-27/__output__.json
/kaggle/input/pm-96835262-at-10-30-2025-18-34-27/numpy-2.3.4-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
/kaggle/input/pm-96835262-at-10-30-2025-18-34-27/install_requirements.sh
/kaggle/input/pm-96835262-at-10-30-2025-18-34-27/custom.css

In [2]:
# load files
train_path = "../input/dsmbc-2025-kaggle-war-bank-marketing-campaign-pre/train.csv"
test_path = "../input/dsmbc-2025-kaggle-war-bank-marketing-campaign-pre/test.csv"

df_train = pd.read_csv(train_path);
df_test = pd.read_csv(test_path);

print(df_train.columns)
print(df_test.columns)

Index(['id', 'age', 'job', 'marital', 'education', 'default', 'housing',
       'loan', 'contact', 'month', 'day_of_week', 'duration', 'campaign',
       'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')
Index(['id', 'age', 'job', 'marital', 'education', 'default', 'housing',
       'loan', 'contact', 'month', 'day_of_week', 'duration', 'campaign',
       'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed'],
      dtype='object')

In [3]:
df_train.head()

,id,age,job,marital,education,default,housing,loan,contact,month,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,25612,49,blue-collar,married,basic.9y,unknown,no,no,cellular,nov,...,4,999,0,nonexistent,-0.1,93.200,-42.0,4.120,5195.8,0
1,26011,37,entrepreneur,married,university.degree,no,no,no,telephone,nov,...,2,999,1,failure,-0.1,93.200,-42.0,4.120,5195.8,0
2,40195,78,retired,married,basic.4y,no,no,no,cellular,jul,...,1,999,0,nonexistent,-1.7,94.215,-40.3,0.870,4991.6,1
3,298,36,admin.,married,university.degree,no,yes,no,telephone,may,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
4,36345,59,retired,divorced,university.degree,no,no,no,cellular,jun,...,2,999,0,nonexistent,-2.9,92.963,-40.8,1.262,5076.2,0

## Data Cleaning

In [4]:
df_train.replace('unknown', np.nan, inplace=True)
df_test.replace('unknown', np.nan, inplace=True)
print(df_train.shape)
df_train.isna().sum()

(32950, 22)

id                   0
age                  0
job                265
marital             65
education         1397
default           6940
housing            796
loan               796
contact              0
month                0
day_of_week          0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx       0
cons.conf.idx        0
euribor3m            0
nr.employed          0
y                    0
dtype: int64

In [5]:
# drop unused features
df_train = df_train.drop(columns='id')
test_id = df_test['id']
df_test = df_test.drop(columns='id')

In [6]:
print(df_train.duplicated().sum())
df_train = df_train.drop_duplicates()

8

In [7]:
print(df_train['job'].unique())
print(df_train['marital'].unique())
print(df_train['education'].unique())
print(df_train['default'].unique())
print(df_train['housing'].unique())
print(df_train['loan'].unique())
print(df_train['contact'].unique())
print(df_train['month'].unique())
print(df_train['day_of_week'].unique())
print(df_train['poutcome'].unique())

print(df_test['job'].unique())
print(df_test['marital'].unique())
print(df_test['education'].unique())
print(df_test['default'].unique())
print(df_test['housing'].unique())
print(df_test['loan'].unique())
print(df_test['contact'].unique())
print(df_test['month'].unique())
print(df_test['day_of_week'].unique())
print(df_test['poutcome'].unique())

['blue-collar' 'entrepreneur' 'retired' 'admin.' 'student' 'services'
 'technician' 'self-employed' 'management' 'unemployed' nan 'housemaid']
['married' 'divorced' 'single' nan]
['basic.9y' 'university.degree' 'basic.4y' 'high.school'
 'professional.course' nan 'basic.6y' 'illiterate']
[nan 'no' 'yes']
['no' 'yes' nan]
['no' 'yes' nan]
['cellular' 'telephone']
['nov' 'jul' 'may' 'jun' 'aug' 'mar' 'oct' 'apr' 'sep' 'dec']
['wed' 'mon' 'tue' 'fri' 'thu']
['nonexistent' 'failure' 'success']
['management' 'unemployed' 'retired' 'entrepreneur' 'admin.' 'blue-collar'
 'self-employed' 'technician' 'services' 'student' 'housemaid' nan]
['divorced' nan 'married' 'single']
['university.degree' 'professional.course' 'basic.4y' 'high.school'
 'basic.9y' nan 'basic.6y' 'illiterate']
['no' nan]
['no' 'yes' nan]
['no' 'yes' nan]
['cellular' 'telephone']
['jul' 'jun' 'mar' 'aug' 'nov' 'sep' 'apr' 'may' 'oct' 'dec']
['tue' 'thu' 'fri' 'wed' 'mon']
['nonexistent' 'failure' 'success']

In [8]:
# Import library sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, classification_report, accuracy_score
from xgboost import XGBClassifier

In [9]:
# manual mapping data train
education_mapping = { 'illiterate': 0, 'basic.4y': 1, 'basic.6y': 2, 'basic.9y': 3, 'high.school': 4, 'professional.course': 5, 'university.degree': 6 }
month_mapping = { 'jan': 0, 'feb': 1, 'mar': 2, 'apr': 3, 'may': 4, 'jun': 5, 'jul': 6, 'aug': 7, 'sep': 8, 'oct': 9, 'nov': 10, 'dec': 11 }
day_mapping = { 'sun': 0, 'mon': 1, 'tue': 2, 'wed': 3, 'thu': 4, 'fri': 5, 'sat': 6 }
poutcome_mapping = { 'nonexistent': 0, 'failure': -1, 'success': 1 }

df_train['education'] = df_train['education'].map(education_mapping)
df_train['poutcome'] = df_train['poutcome'].map(poutcome_mapping)
df_train['day_of_week'] = df_train['day_of_week'].map(day_mapping)
df_train['month'] = df_train['month'].map(month_mapping)

df_train['day_sin'] = np.sin(2 * np.pi * df_train['day_of_week'] / 7)
df_train['day_cos'] = np.cos(2 * np.pi * df_train['day_of_week'] / 7)
df_train['month_sin'] = np.sin(2 * np.pi * df_train['month'] / 12)
df_train['month_cos'] = np.cos(2 * np.pi * df_train['month'] / 12)

df_train = df_train.drop(columns=['day_of_week', 'month']);

In [10]:
# manual mapping data test
df_test['education'] = df_test['education'].map(education_mapping)
df_test['poutcome'] = df_test['poutcome'].map(poutcome_mapping)
df_test['day_of_week'] = df_test['day_of_week'].map(day_mapping)
df_test['month'] = df_test['month'].map(month_mapping)

df_test['day_sin'] = np.sin(2 * np.pi * df_test['day_of_week'] / 7)
df_test['day_cos'] = np.cos(2 * np.pi * df_test['day_of_week'] / 7)
df_test['month_sin'] = np.sin(2 * np.pi * df_test['month'] / 12)
df_test['month_cos'] = np.cos(2 * np.pi * df_test['month'] / 12)

df_test = df_test.drop(columns=['day_of_week', 'month']);

In [11]:
# Pipeline preprocessing
num_cols = df_train.select_dtypes(include=['int64', 'float64']).columns.to_list()
num_cols.remove('y')

label_encoding_cols = ['default', 'housing', 'loan']
one_hot_encoding_cols = ['job', 'contact', 'marital']

numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

label_encoder = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder())
])

one_hot_encoder = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num_trans', numerical_transformer, num_cols),
        ('label_encode', label_encoder, label_encoding_cols),
        ('one_hot_encode', one_hot_encoder, one_hot_encoding_cols)
    ],
    remainder='passthrough'
)

## Modelling & Predicting

### Pipeline RF

In [12]:
# define features & target
X = df_train.drop(columns=['y'])
y = df_train['y']
df_train = X

In [13]:
# split data
X_train, X_val, y_train, y_val = train_test_split(
    X, y, 
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [14]:
# model
model_rf = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

In [15]:
X.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,day_sin,day_cos,month_sin,month_cos
0,49,blue-collar,married,3.0,NaN,no,no,cellular,227,4,...,0,-0.1,93.200,-42.0,4.120,5195.8,0.433884,-0.900969,-8.660254e-01,0.500000
1,37,entrepreneur,married,6.0,no,no,no,telephone,202,2,...,-1,-0.1,93.200,-42.0,4.120,5195.8,0.433884,-0.900969,-8.660254e-01,0.500000
2,78,retired,married,1.0,no,no,no,cellular,1148,1,...,0,-1.7,94.215,-40.3,0.870,4991.6,0.781831,0.623490,1.224647e-16,-1.000000
3,36,admin.,married,6.0,no,yes,no,telephone,120,2,...,0,1.1,93.994,-36.4,4.857,5191.0,0.781831,0.623490,8.660254e-01,-0.500000
4,59,retired,divorced,6.0,no,no,no,cellular,368,2,...,0,-2.9,92.963,-40.8,1.262,5076.2,0.974928,-0.222521,5.000000e-01,-0.866025

In [16]:
# run training
clf_rf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', model_rf)
])
clf_rf.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num_trans',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'education',
                                                   'duration', 'campaign',
                                                   'pdays', 'previous',
                                                   'poutcome', 'emp.var.rate',
                                                   'cons.price.idx',
                                                   'cons.conf.idx', 'euribor3m',
                                                   'nr.employed', 'day_sin',
                                                   'day_cos', 'month_sin...
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder())]),
                                                  ['default', 'housing',
                                                   'loan']),
                                                 ('one_hot_encode',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['job', 'contact',
                                                   'marital'])])),
                ('model',
                 RandomForestClassifier(class_weight='balanced', n_jobs=-1,
                                        random_state=42))])

In [17]:
# predict 
y_pred_rf = clf_rf.predict(X_val)
f1_rf = f1_score(y_val, y_pred_rf)
print(f"F1-Score : {f1_rf}")

acc = accuracy_score(y_val, y_pred_rf)
print(f"Akurasi: {acc}")

F1-Score : 0.5141430948419301
Akurasi: 0.911367430566095

### Pipeline XGB

In [18]:
print(y_train.value_counts())
ratio = y_train.value_counts()[0] / y_train.value_counts()[1]

y
0    23383
1     2970
Name: count, dtype: int64

In [19]:
# define and train XGBoost model
model_xgb = XGBClassifier(scale_pos_weight=ratio, random_state=42)

clf_xgb = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', model_xgb)
])
clf_xgb.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num_trans',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'education',
                                                   'duration', 'campaign',
                                                   'pdays', 'previous',
                                                   'poutcome', 'emp.var.rate',
                                                   'cons.price.idx',
                                                   'cons.conf.idx', 'euribor3m',
                                                   'nr.employed', 'day_sin',
                                                   'day_cos', 'month_sin...
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, random_state=42, ...))])

In [20]:
# predict
y_pred_xgb = clf_xgb.predict(X_val)
f1_xgb = f1_score(y_val, y_pred_xgb)
print(f"F1-Score : {f1_xgb}")

acc_xgb = accuracy_score(y_val, y_pred_xgb)
print(f"Akurasi: {acc_xgb}")

F1-Score : 0.6136475208640156
Akurasi: 0.8805585066019123

### Pipeline LightGBM

In [21]:
from lightgbm import LGBMClassifier

In [22]:
model_lgbm = LGBMClassifier(
    is_unbalance=True, 
    random_state=42, 
    n_jobs=-1
)
clf_lgbm = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', model_lgbm)
])
clf_lgbm.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 2970, number of negative: 23383
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004085 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 670
[LightGBM] [Info] Number of data points in the train set: 26353, number of used features: 34
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.112701 -> initscore=-2.063447
[LightGBM] [Info] Start training from score -2.063447

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num_trans',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'education',
                                                   'duration', 'campaign',
                                                   'pdays', 'previous',
                                                   'poutcome', 'emp.var.rate',
                                                   'cons.price.idx',
                                                   'cons.conf.idx', 'euribor3m',
                                                   'nr.employed', 'day_sin',
                                                   'day_cos', 'month_sin...
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder())]),
                                                  ['default', 'housing',
                                                   'loan']),
                                                 ('one_hot_encode',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['job', 'contact',
                                                   'marital'])])),
                ('model',
                 LGBMClassifier(is_unbalance=True, n_jobs=-1,
                                random_state=42))])

In [23]:
# Accuracy
y_pred_lgbm = clf_lgbm.predict(X_val)
f1_lgbm = f1_score(y_val, y_pred_xgb)
print(f"F1-Score : {f1_lgbm}")

acc_lgbm = accuracy_score(y_val, y_pred_lgbm)
print(f"Akurasi: {acc_lgbm}")

F1-Score : 0.6136475208640156
Akurasi: 0.8664440734557596

## Submission

In [24]:
# predict 
y_pred_final = clf_lgbm.predict(df_test)

In [25]:
# submit competition
submission = pd.DataFrame({
   "id": test_id,
   "y": y_pred_final
})
submission.to_csv("submission.csv", index=False)