In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('all_months_clean.csv', sep=";")
df.sort_values(by='num_product_categories', ascending=False)

,order_id,total_qty,total_weight_gr,total_returned_qty,Total Diskon,product_categories,num_product_categories,Status Pesanan,Alasan Pembatalan,Opsi Pengiriman,Metode Pembayaran,Kota/Kabupaten,Provinsi,Ongkos Kirim Dibayar oleh Pembeli,Estimasi Potongan Biaya Pengiriman,Total Pembayaran,Perkiraan Ongkos Kirim,Waktu Pesanan Dibuat,source_file
74,ORD_0000075,22,97740,0,0,"Aksesoris ID Card, Bangku / Kursi Kecil, Botol...",11,Batal,Dibatalkan oleh Pembeli. Alasan: Need to chang...,Kargo-JNE Trucking (JTR),Online Payment,KOTA SURABAYA,JAWA TIMUR,0,0,0,39900,2024-04-12 05:44,AprilSales2024.xlsx
2617,ORD_0002618,13,74100,0,0,"Botol / Gelas / Mug, Celengan, Gantungan Baju ...",11,Selesai,NaN,Instant (Versi Lama)-SPX Instant (Versi Lama),Saldo ShopeePay,KOTA TANGERANG,BANTEN,0,18000,135572,18000,2025-08-01 10:59,AugustSales2025.xlsx
19518,ORD_0019519,11,39160,2,0,"Aksesoris Mandi, Botol / Gelas / Mug, Gantunga...",9,Selesai,NaN,Hemat Kargo-SPX Hemat,SPayLater,KAB. TANGERANG,BANTEN,12000,20000,83831,32000,2024-09-25 11:21,SeptemberSales2024.xlsx
91,ORD_0000092,18,88110,0,0,"Bangku / Kursi Kecil, Botol / Gelas / Mug, Nam...",9,Batal,Dibatalkan oleh Pembeli. Alasan: Need to chang...,Kargo-JNE Trucking (JTR),Saldo ShopeePay,KOTA SURABAYA,JAWA TIMUR,0,0,0,39900,2024-04-13 07:30,AprilSales2024.xlsx
687,ORD_0000688,8,60400,0,0,"Aksesoris Pintu, Nampan / Tray, Other, Peralat...",8,Selesai,NaN,Kargo-J&T Cargo,Saldo ShopeePay,KOTA JAKARTA PUSAT,DKI JAKARTA,1000,20000,169200,21000,2025-04-10 12:14,AprilSales2025.xlsx
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7197,ORD_0007198,1,1000,0,0,Mangkok Sambal / Saus,1,Selesai,NaN,Hemat Kargo-SPX Hemat,SPayLater,KAB. CIAMIS,JAWA BARAT,0,16000,135301,16000,2025-01-04 14:55,JanuarySales2025.xlsx
7196,ORD_0007197,1,500,0,0,Celengan,1,Batal,Dibatalkan secara otomatis oleh sistem. Alasan...,Reguler (Cashless),Online Payment,KOTA JAKARTA UTARA,DKI JAKARTA,0,0,0,10000,2025-01-04 14:50,JanuarySales2025.xlsx
7195,ORD_0007196,2,400,0,0,Mangkok Sambal / Saus,1,Selesai,NaN,SPX Hemat,COD (Bayar di Tempat),KAB. ENDE,NUSA TENGGARA TIMUR (NTT),38900,25000,72656,63900,2025-01-04 14:47,JanuarySales2025.xlsx
7194,ORD_0007195,1,500,0,0,Keranjang,1,Batal,Dibatalkan oleh Pembeli. Alasan: Lainnya/ beru...,Reguler (Cashless)-SPX Standard,COD (Bayar di Tempat),KOTA CILEGON,BANTEN,0,0,0,10000,2025-01-04 13:38,JanuarySales2025.xlsx
7203,ORD_0007204,1,200,0,0,Mangkok Sambal / Saus,1,Selesai,NaN,Reguler (Cashless)-SPX Standard,COD (Bayar di Tempat),KAB. INDRAMAYU,JAWA BARAT,0,17000,17120,17000,2025-01-04 17:39,JanuarySales2025.xlsx

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20848 entries, 0 to 20847
Data columns (total 19 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   order_id                            20848 non-null  object
 1   total_qty                           20848 non-null  int64
 2   total_weight_gr                     20848 non-null  int64
 3   total_returned_qty                  20848 non-null  int64
 4   Total Diskon                        20848 non-null  int64
 5   product_categories                  20848 non-null  object
 6   num_product_categories              20848 non-null  int64
 7   Status Pesanan                      20848 non-null  object
 8   Alasan Pembatalan                   2830 non-null   object
 9   Opsi Pengiriman                     20848 non-null  object
 10  Metode Pembayaran                   20848 non-null  object
 11  Kota/Kabupaten                      20848 non-null  object
 12  Provinsi                            20848 non-null  object
 13  Ongkos Kirim Dibayar oleh Pembeli   20848 non-null  int64
 14  Estimasi Potongan Biaya Pengiriman  20848 non-null  int64
 15  Total Pembayaran                    20848 non-null  int64
 16  Perkiraan Ongkos Kirim              20848 non-null  int64
 17  Waktu Pesanan Dibuat                18868 non-null  object
 18  source_file                         20848 non-null  object
dtypes: int64(9), object(10)
memory usage: 3.0+ MB

In [21]:
df['Alasan Pembatalan'].unique()

array([nan, 'Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan yang Ada',
       'Dibatalkan oleh Pembeli. Alasan: Lainnya/ berubah pikiran',
       'Dibatalkan secara otomatis oleh sistem. Alasan: Pengiriman gagal',
       'Dibatalkan secara otomatis oleh sistem. Alasan: Penjual tidak mengatur pengiriman tepat waktu',
       'Dibatalkan oleh Pembeli. Alasan: Need to change delivery address',
       'Dibatalkan secara otomatis oleh sistem. Alasan: Pesanan belum dibayar',
       'Dibatalkan secara otomatis oleh sistem. Alasan: Penjual gagal mengirimkan pesanan tepat waktu',
       'Dibatalkan oleh Pembeli. Alasan: Perlu mengubah alamat pengiriman',
       'Dibatalkan oleh Pembeli. Alasan: Perlu mengubah pesanan',
       'Dibatalkan oleh Penjual. Alasan: Produk habis',
       'Dibatalkan oleh Pembeli. Alasan: Menemukan yang lebih murah',
       'Dibatalkan oleh Pembeli. Alasan: Penjual tidak responsif terhadap pertanyaan Pembeli',
       'Dibatalkan oleh Pembeli. Alasan: Proses pembayaran sulit',
       'Dibatalkan oleh Pembeli. Alasan: Lainnya',
       'Dibatalkan secara otomatis oleh sistem. Alasan: Paket hilang di perjalanan. Kompensasi yang memenuhi syarat telah dikreditkan ke Saldo Penjual-mu.',
       'Dibatalkan oleh Pembeli. Alasan: Perlu mengubah Voucher',
       'Dibatalkan oleh Pembeli. Alasan: Tidak ingin membeli lagi',
       'Dibatalkan secara otomatis oleh sistem. Alasan: Lainnya'],
      dtype=object)

In [13]:
df[(df['order_id'] == 'ORD_0000075')]

,order_id,total_qty,total_weight_gr,total_returned_qty,Total Diskon,product_categories,num_product_categories,Status Pesanan,Alasan Pembatalan,Opsi Pengiriman,Metode Pembayaran,Kota/Kabupaten,Provinsi,Ongkos Kirim Dibayar oleh Pembeli,Estimasi Potongan Biaya Pengiriman,Total Pembayaran,Perkiraan Ongkos Kirim,Waktu Pesanan Dibuat,source_file
74,ORD_0000075,22,97740,0,0,"Aksesoris ID Card, Bangku / Kursi Kecil, Botol...",11,Batal,Dibatalkan oleh Pembeli. Alasan: Need to chang...,Kargo-JNE Trucking (JTR),Online Payment,KOTA SURABAYA,JAWA TIMUR,0,0,0,39900,2024-04-12 05:44,AprilSales2024.xlsx

In [6]:
df_batal = df[(df['Status Pesanan'] == 'Batal')]
# df_batal = df_batal[['Ongkos Kirim Dibayar oleh Pembeli', 'Total Pembayaran', 'Status Pesanan']]

In [7]:
df_batal[['total_qty', 'total_returned_qty']]

       total_qty  total_returned_qty
4              3                   0
6              1                   0
8              1                   0
10             2                   0
11             1                   0
...          ...                 ...
20812          2                   0
20815          4                   0
20822          1                   0
20833          2                   0
20834          2                   0

[2830 rows x 2 columns]

In [18]:
df_batal

       Ongkos Kirim Dibayar oleh Pembeli  Total Pembayaran Status Pesanan
4                                      0                 0          Batal
6                                      0                 0          Batal
8                                      0                 0          Batal
10                                     0                 0          Batal
11                                     0                 0          Batal
...                                  ...               ...            ...
20812                                  0                 0          Batal
20815                                  0                 0          Batal
20822                                  0                 0          Batal
20833                                  0                 0          Batal
20834                                  0                 0          Batal

[2830 rows x 3 columns]

In [19]:
df_batal[(df['Total Pembayaran']) != 0]

/tmp/ipykernel_6888/4143517519.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_batal[(df['Total Pembayaran']) != 0]

Empty DataFrame
Columns: [Ongkos Kirim Dibayar oleh Pembeli, Total Pembayaran, Status Pesanan]
Index: []

In [10]:
df.head()

,order_id,total_qty,total_weight_gr,total_returned_qty,Total Diskon,product_categories,num_product_categories,Status Pesanan,Alasan Pembatalan,Opsi Pengiriman,Metode Pembayaran,Kota/Kabupaten,Provinsi,Ongkos Kirim Dibayar oleh Pembeli,Estimasi Potongan Biaya Pengiriman,Total Pembayaran,Perkiraan Ongkos Kirim,Waktu Pesanan Dibuat,source_file
0,ORD_0000001,2,2000,0,0,Celengan,1,Selesai,NaN,Reguler (Cashless)-SPX Standard,Saldo ShopeePay,KOTA SERANG,BANTEN,0,10000,38300,10000,2024-04-01 00:15,AprilSales2024.xlsx
1,ORD_0000002,1,500,0,0,Celengan,1,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA SEMARANG,JAWA TENGAH,0,14500,18576,14500,2024-04-01 01:47,AprilSales2024.xlsx
2,ORD_0000003,1,500,0,0,Celengan,1,Selesai,NaN,Hemat Kargo-SPX Hemat,SeaBank Bayar Instan,KAB. BOGOR,JAWA BARAT,0,8000,7069,8000,2024-04-01 04:25,AprilSales2024.xlsx
3,ORD_0000004,2,400,0,0,Mangkok Sambal / Saus,1,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA JAMBI,JAMBI,0,20000,32200,20000,2024-04-01 04:41,AprilSales2024.xlsx
4,ORD_0000005,3,3600,0,0,"Keranjang, Other, Tempat Nasi",3,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA TANGERANG,BANTEN,0,0,0,8000,2024-04-01 06:12,AprilSales2024.xlsx

In [5]:
df['product_categories'].value_counts()

product_categories
Celengan                                                                                             5514
Mangkok Sambal / Saus                                                                                3609
Aksesoris Pintu                                                                                      2721
Nampan / Tray                                                                                        1308
Seal / Baut / Roof                                                                                    672
                                                                                                     ...
Aksesoris ID Card, Aksesoris Pintu, Botol / Gelas / Mug, Peralatan Makan, Sapu / Pembersih Lantai       1
Aksesoris Mandi, Celengan, Toples / Sealware                                                            1
Aksesoris Mandi, Botol / Gelas / Mug, Mangkok Sambal / Saus, Other, Peralatan Kamar Mandi               1
Celengan, Perlengkapan Packing, Plastik / Wadah Plastik                                                 1
Aksesoris ID Card, Teko / Jug                                                                           1
Name: count, Length: 679, dtype: int64

In [7]:
df['product_categories'].unique()

array(['Celengan', 'Mangkok Sambal / Saus',
       'Keranjang, Other, Tempat Nasi', 'Nampan / Tray',
       'Aksesoris Mandi, Celengan, Keranjang', 'Toples / Sealware',
       'Other', 'Celengan, Peralatan Kamar Mandi', 'Rak / Rak Serbaguna',
       'Keranjang', 'Perlengkapan Packing, Toples / Sealware',
       'Plastik / Wadah Plastik', 'Celengan, Other',
       'Stempel / Alat Kantor', 'Celengan, Plastik / Wadah Plastik',
       'Aksesoris ID Card, Bangku / Kursi Kecil, Botol / Gelas / Mug, Mangkok Sambal / Saus, Nampan / Tray, Peralatan Makan, Perlengkapan Packing, Plastik / Wadah Plastik, Saringan / Strainer, Talenan, Toples / Sealware',
       'Peralatan Kamar Mandi',
       'Bangku / Kursi Kecil, Botol / Gelas / Mug, Nampan / Tray, Peralatan Makan, Perlengkapan Packing, Plastik / Wadah Plastik, Saringan / Strainer, Talenan, Toples / Sealware',
       'Mangkok Sambal / Saus, Other, Tempat Sampah',
       'Nampan / Tray, Plastik / Wadah Plastik', 'Lunch Box / Rantang',
       'Peralatan Kamar Mandi, Perlengkapan Packing',
       'Perlengkapan Packing', 'Aksesoris Mandi, Keranjang',
       'Celengan, Perlengkapan Packing',
       'Botol / Gelas / Mug, Celengan, Nampan / Tray', 'Mangkok',
       'Seal / Baut / Roof', 'Peralatan Makan', 'Piring',
       'Gantungan Baju / Hanger', 'Celengan, Keranjang',
       'Botol / Gelas / Mug, Mangkok Sambal / Saus',
       'Perlengkapan Packing, Rak / Rak Serbaguna', 'Tempat Nasi',
       'Other, Perlengkapan Packing, Pisau / Alat Potong', 'Teko / Jug',
       'Baskom / Mangkok Besar, Mangkok Sambal / Saus, Other, Perlengkapan Packing, Sapu / Pembersih Lantai, Tempat Nasi, Toples / Sealware',
       'Other, Rak / Rak Serbaguna', 'Cobek / Ulekan',
       'Aksesoris ID Card', 'Mangkok Sambal / Saus, Pisau / Alat Potong',
       'Celengan, Peralatan Makan, Toples / Sealware',
       'Bangku / Kursi Kecil, Nampan / Tray, Perlengkapan Packing, Saringan / Strainer, Talenan',
       'Botol / Gelas / Mug, Keranjang, Plastik / Wadah Plastik',
       'Celengan, Sapu / Pembersih Lantai', 'Keranjang, Nampan / Tray',
       'Aksesoris Pintu, Gantungan Baju / Hanger',
       'Baskom / Mangkok Besar, Celengan',
       'Baskom / Mangkok Besar, Saringan / Strainer',
       'Bangku / Kursi Kecil', 'Aksesoris Pintu',
       'Baskom / Mangkok Besar', 'Sapu / Pembersih Lantai',
       'Celengan, Perlengkapan Packing, Pisau / Alat Potong',
       'Nampan / Tray, Spatula', 'Other, Perlengkapan Packing',
       'Pengolah Bumbu / Sayur', 'Botol / Gelas / Mug',
       'Pisau / Alat Potong',
       'Keranjang, Plastik / Wadah Plastik, Sikat / Pembersih',
       'Bangku / Kursi Kecil, Nampan / Tray',
       'Baskom / Mangkok Besar, Keranjang',
       'Aksesoris Pintu, Nampan / Tray, Other, Peralatan Makan, Pisau / Alat Potong, Plastik / Wadah Plastik, Rak / Rak Serbaguna, Sapu / Pembersih Lantai',
       'Gantungan Baju / Hanger, Mangkok Sambal / Saus, Nampan / Tray, Other, Pisau / Alat Potong, Saringan / Strainer',
       'Other, Tempat Nasi', 'Aksesoris Pintu, Toples / Sealware',
       'Botol / Gelas / Mug, Piring',
       'Botol / Gelas / Mug, Keranjang, Mangkok Sambal / Saus',
       'Aksesoris Pintu, Other, Perlengkapan Packing, Sapu / Pembersih Lantai, Spatula',
       'Celengan, Mangkok, Nampan / Tray', 'Mangkok Sambal / Saus, Other',
       'Botol / Gelas / Mug, Celengan', 'Aksesoris Pintu, Celengan',
       'Baskom / Mangkok Besar, Other, Peralatan Makan, Pisau / Alat Potong',
       'Keranjang, Other, Pisau / Alat Potong', 'Pot Tanaman / Bunga',
       'Baskom / Mangkok Besar, Mangkok Sambal / Saus, Other',
       'Keranjang, Other', 'Aksesoris Pintu, Keranjang',
       'Celengan, Other, Plastik / Wadah Plastik',
       'Baskom / Mangkok Besar, Piring',
       'Baskom / Mangkok Besar, Mangkok Sambal / Saus',
       'Celengan, Mangkok', 'Aksesoris Pintu, Sikat / Pembersih',
       'Saringan / Strainer', 'Botol / Gelas / Mug, Keranjang',
       'Mangkok Sambal / Saus, Perlengkapan Packing',
       'Keranjang, Piring, Rak / Rak Serbaguna, Toples / Sealware',
       'Mangkok Sambal / Saus, Peralatan Makan',
       'Baskom / Mangkok Besar, Perlengkapan Packing',
       'Aksesoris Pintu, Keranjang, Other, Pisau / Alat Potong',
       'Aksesoris Pintu, Keranjang, Other',
       'Botol / Gelas / Mug, Keranjang, Mangkok Sambal / Saus, Peralatan Makan, Toples / Sealware',
       'Nampan / Tray, Perlengkapan Packing',
       'Aksesoris Pintu, Nampan / Tray', 'Aksesoris Pintu, Gayung',
       'Mangkok Sambal / Saus, Peralatan Makan, Perkakas',
       'Keranjang, Teko / Jug', 'Peralatan Makan, Saringan / Strainer',
       'Aksesoris Pintu, Baskom / Mangkok Besar',
       'Lunch Box / Rantang, Mangkok Sambal / Saus, Other',
       'Botol / Gelas / Mug, Perlengkapan Packing, Teko / Jug',
       'Botol / Gelas / Mug, Peralatan Makan',
       'Mangkok Sambal / Saus, Nampan / Tray',
       'Mangkok Sambal / Saus, Saringan / Strainer',
       'Botol / Gelas / Mug, Stempel / Alat Kantor',
       'Botol / Gelas / Mug, Pisau / Alat Potong', 'Aksesoris Mandi',
       'Botol / Gelas / Mug, Peralatan Makan, Saringan / Strainer',
       'Aksesoris Mandi, Celengan, Peralatan Kamar Mandi, Sapu / Pembersih Lantai',
       'Bangku / Kursi Kecil, Gantungan Baju / Hanger',
       'Mangkok Sambal / Saus, Teko / Jug',
       'Aksesoris Pintu, Peralatan Makan, Perkakas', 'Spatula',
       'Celengan, Other, Saringan / Strainer',
       'Botol / Gelas / Mug, Mangkok Sambal / Saus, Saringan / Strainer',
       'Baskom / Mangkok Besar, Tempat Nasi', 'Celengan, Gayung',
       'Celengan, Other, Peralatan Makan',
       'Aksesoris Mandi, Peralatan Makan, Toples / Sealware',
       'Teko / Jug, Tempat Nasi',
       'Aksesoris Pintu, Peralatan Kamar Mandi, Plastik / Wadah Plastik, Sikat / Pembersih',
       'Botol / Gelas / Mug, Other, Perlengkapan Packing, Sapu / Pembersih Lantai',
       'Baskom / Mangkok Besar, Celengan, Other, Teko / Jug',
       'Celengan, Plastik / Wadah Plastik, Sikat / Pembersih',
       'Keranjang, Saringan / Strainer',
       'Mangkok Sambal / Saus, Peralatan Makan, Spatula',
       'Keranjang, Perlengkapan Packing', 'Aksesoris Motor', 'Gayung',
       'Aksesoris Pintu, Other, Perkakas', 'Celengan, Keranjang, Other',
       'Saringan / Strainer, Spatula',
       'Baskom / Mangkok Besar, Gayung, Other',
       'Lunch Box / Rantang, Toples / Sealware',
       'Keranjang, Mangkok Sambal / Saus, Other',
       'Aksesoris Pintu, Sapu / Pembersih Lantai',
       'Baskom / Mangkok Besar, Mangkok Sambal / Saus, Other, Pisau / Alat Potong, Saringan / Strainer, Sikat / Pembersih, Toples / Sealware',
       'Talenan', 'Peralatan Makan, Plastik / Wadah Plastik',
       'Mangkok Sambal / Saus, Other, Perlengkapan Packing',
       'Mangkok Sambal / Saus, Other, Sikat / Pembersih',
       'Botol / Gelas / Mug, Mangkok Sambal / Saus, Nampan / Tray, Other',
       'Celengan, Other, Perlengkapan Packing',
       'Bangku / Kursi Kecil, Celengan',
       'Bangku / Kursi Kecil, Celengan, Peralatan Makan, Rak / Rak Serbaguna',
       'Baskom / Mangkok Besar, Other',
       'Botol / Gelas / Mug, Celengan, Mangkok Sambal / Saus, Rak / Rak Serbaguna',
       'Celengan, Other, Pisau / Alat Potong, Saringan / Strainer',
       'Perlengkapan Packing, Teko / Jug',
       'Botol / Gelas / Mug, Lunch Box / Rantang',
       'Gayung, Lunch Box / Rantang, Saringan / Strainer',
       'Bangku / Kursi Kecil, Peralatan Makan, Saringan / Strainer',
       'Celengan, Other, Perlengkapan Packing, Plastik / Wadah Plastik',
       'Mangkok Sambal / Saus, Rak / Rak Serbaguna',
       'Perlengkapan Packing, Plastik / Wadah Plastik',
       'Mangkok Sambal / Saus, Nampan / Tray, Other',
       'Celengan, Perlengkapan Packing, Sapu / Pembersih Lantai',
       'Celengan, Sapu / Pembersih Lantai, Sikat / Pembersih',
       'Nampan / Tray, Other, Perlengkapan Packing',
       'Lunch Box / Rantang, Peralatan Makan, Spatula',
       'Aksesoris Pintu, Other',
       'Mangkok Sambal / Saus, Sapu / Pembersih Lantai',
       'Other, Saringan / Strainer', 'Gantungan Baju / Hanger, Keranjang',
       'Peralatan Makan, Plastik / Wadah Plastik, Saringan / Strainer',
       'Botol / Gelas / Mug, Celengan, Gantungan Baju / Hanger, Keranjang, Lunch Box / Rantang, Other, Sapu / Pembersih Lantai, Saringan / Strainer, Talenan, Tempat Nasi, Toples / Sealware',
       'Aksesoris Mandi, Peralatan Kamar Mandi, Toples / Sealware',
       'Celengan, Lunch Box / Rantang',
       'Aksesoris Pintu, Peralatan Makan',
       'Aksesoris Pintu, Other, Sapu / Pembersih Lantai',
       'Lunch Box / Rantang, Mangkok Sambal / Saus',
       'Botol / Gelas / Mug, Mangkok Sambal / Saus, Nampan / Tray',
       'Rak / Rak Serbaguna, Sikat / Pembersih', 'Sikat / Pembersih',
       'Nampan / Tray, Peralatan Makan',
       'Baskom / Mangkok Besar, Nampan / Tray',
       'Mangkok Sambal / Saus, Nampan / Tray, Peralatan Makan',
       'Bangku / Kursi Kecil, Baskom / Mangkok Besar, Plastik / Wadah Plastik',
       'Botol / Gelas / Mug, Mangkok, Nampan / Tray',
       'Botol / Gelas / Mug, Mangkok Sambal / Saus, Other, Piring',
       'Peralatan Makan, Piring',
       'Other, Peralatan Kamar Mandi, Sikat / Pembersih',
       'Nampan / Tray, Peralatan Kamar Mandi, Plastik / Wadah Plastik',
       'Aksesoris Pintu, Celengan, Mangkok, Other, Saringan / Strainer',
       'Aksesoris Pintu, Botol / Gelas / Mug, Other',
       'Aksesoris Pintu, Celengan, Keranjang',
       'Mangkok, Other, Peralatan Makan, Tempat Nasi',
       'Peralatan Makan, Toples / Sealware',
       'Mangkok Sambal / Saus, Other, Saringan / Strainer',
       'Keranjang, Mangkok Sambal / Saus, Other, Peralatan Makan, Spatula',
       'Mangkok Sambal / Saus, Other, Plastik / Wadah Plastik',
       'Celengan, Other, Peralatan Makan, Toples / Sealware',
       'Keranjang, Mangkok Sambal / Saus',
       'Botol / Gelas / Mug, Mangkok Sambal / Saus, Other, Plastik / Wadah Plastik',
       'Keranjang, Peralatan Makan',
       'Peralatan Makan, Saringan / Strainer, Sikat / Pembersih, Teko / Jug',
       'Botol / Gelas / Mug, Nampan / Tray, Saringan / Strainer',
       'Botol / Gelas / Mug, Tempat Nasi', 'Celengan, Peralatan Makan',
       'Mangkok Sambal / Saus, Peralatan Makan, Plastik / Wadah Plastik',
       'Celengan, Rak / Rak Serbaguna',
       'Lunch Box / Rantang, Perlengkapan Packing',
       'Baskom / Mangkok Besar, Other, Peralatan Makan, Saringan / Strainer',
       'Celengan, Keranjang, Plastik / Wadah Plastik',
       'Botol / Gelas / Mug, Spatula',
       'Botol / Gelas / Mug, Other, Peralatan Kamar Mandi',
       'Keranjang, Mangkok Sambal / Saus, Peralatan Makan',
       'Aksesoris Pintu, Plastik / Wadah Plastik',
       'Mangkok Sambal / Saus, Talenan',
       'Aksesoris Pintu, Perlengkapan Packing',
       'Bangku / Kursi Kecil, Keranjang, Lunch Box / Rantang, Other, Peralatan Makan, Plastik / Wadah Plastik, Sikat / Pembersih',
       'Celengan, Gantungan Baju / Hanger',
       'Aksesoris Mandi, Baskom / Mangkok Besar, Botol / Gelas / Mug, Celengan, Plastik / Wadah Plastik',
       'Aksesoris Pintu, Other, Sikat / Pembersih',
       'Botol / Gelas / Mug, Mangkok Sambal / Saus, Peralatan Makan',
       'Other, Sapu / Pembersih Lantai',
       'Baskom / Mangkok Besar, Spatula', 'Aksesoris Pintu, Piring',
       'Aksesoris Pintu, Bangku / Kursi Kecil',
       'Aksesoris ID Card, Aksesoris Pintu, Gantungan Baju / Hanger',
       'Mangkok Sambal / Saus, Other, Peralatan Makan',
       'Gantungan Baju / Hanger, Other', 'Other, Teko / Jug',
       'Nampan / Tray, Other, Piring',
       'Mangkok Sambal / Saus, Other, Talenan',
       'Aksesoris Pintu, Baskom / Mangkok Besar, Keranjang, Other, Talenan',
       'Botol / Gelas / Mug, Keranjang, Saringan / Strainer',
       'Other, Sikat / Pembersih', 'Aksesoris Pintu, Saringan / Strainer',
       'Cobek / Ulekan, Keranjang, Mangkok',
       'Bangku / Kursi Kecil, Sapu / Pembersih Lantai',
       'Other, Plastik / Wadah Plastik',
       'Cobek / Ulekan, Sapu / Pembersih Lantai',
       'Aksesoris Pintu, Plastik / Wadah Plastik, Saringan / Strainer',
       'Keranjang, Sapu / Pembersih Lantai',
       'Gantungan Baju / Hanger, Keranjang, Mangkok Sambal / Saus, Saringan / Strainer, Talenan',
       'Botol / Gelas / Mug, Celengan, Sapu / Pembersih Lantai',
       'Mangkok Sambal / Saus, Peralatan Kamar Mandi, Saringan / Strainer',
       'Aksesoris Pintu, Other, Pengolah Bumbu / Sayur',
       'Baskom / Mangkok Besar, Celengan, Keranjang',
       'Botol / Gelas / Mug, Mangkok',
       'Mangkok Sambal / Saus, Pengolah Bumbu / Sayur',
       'Lunch Box / Rantang, Rak / Rak Serbaguna',
       'Other, Pisau / Alat Potong, Saringan / Strainer',
       'Aksesoris Pintu, Botol / Gelas / Mug, Plastik / Wadah Plastik',
       'Mangkok Sambal / Saus, Other, Peralatan Makan, Tempat Nasi',
       'Aksesoris Pintu, Baskom / Mangkok Besar, Other, Pengolah Bumbu / Sayur, Perlengkapan Packing',
       'Aksesoris Pintu, Seal / Baut / Roof',
       'Aksesoris Pintu, Peralatan Kamar Mandi',
       'Mangkok Sambal / Saus, Piring',
       'Aksesoris Mandi, Celengan, Mangkok Sambal / Saus, Other',
       'Nampan / Tray, Plastik / Wadah Plastik, Rak / Rak Serbaguna',
       'Mangkok Sambal / Saus, Other, Plastik / Wadah Plastik, Saringan / Strainer',
       'Botol / Gelas / Mug, Mangkok Sambal / Saus, Other, Spatula',
       'Keranjang, Mangkok', 'Gayung, Toples / Sealware',
       'Aksesoris Mandi, Celengan',
       'Celengan, Keranjang, Other, Saringan / Strainer',
       'Mangkok Sambal / Saus, Peralatan Kamar Mandi',
       'Celengan, Sikat / Pembersih',
       'Celengan, Nampan / Tray, Sikat / Pembersih',
       'Gayung, Mangkok Sambal / Saus', 'Celengan, Saringan / Strainer',
       'Lunch Box / Rantang, Saringan / Strainer',
       'Keranjang, Rak / Rak Serbaguna',
       'Aksesoris Pintu, Keranjang, Mangkok, Other, Peralatan Kamar Mandi, Peralatan Makan',
       'Botol / Gelas / Mug, Peralatan Makan, Pisau / Alat Potong, Talenan',
       'Gantungan Baju / Hanger, Mangkok Sambal / Saus',
       'Celengan, Mangkok Sambal / Saus',
       'Bangku / Kursi Kecil, Nampan / Tray, Pisau / Alat Potong',
       'Keranjang, Spatula', 'Aksesoris ID Card, Pisau / Alat Potong',
       'Baskom / Mangkok Besar, Cobek / Ulekan, Other, Pengolah Bumbu / Sayur',
       'Piring, Saringan / Strainer',
       'Baskom / Mangkok Besar, Botol / Gelas / Mug, Other, Saringan / Strainer',
       'Aksesoris Pintu, Gayung, Sikat / Pembersih',
       'Aksesoris Pintu, Mangkok Sambal / Saus',
       'Rak / Rak Serbaguna, Sapu / Pembersih Lantai',
       'Baskom / Mangkok Besar, Pisau / Alat Potong',
       'Other, Plastik / Wadah Plastik, Sikat / Pembersih',
       'Botol / Gelas / Mug, Mangkok Sambal / Saus, Teko / Jug',
       'Other, Plastik / Wadah Plastik, Seal / Baut / Roof',
       'Baskom / Mangkok Besar, Mangkok Sambal / Saus, Sikat / Pembersih',
       'Baskom / Mangkok Besar, Mangkok Sambal / Saus, Other, Rak / Rak Serbaguna',
       'Perkakas',
       'Aksesoris Pintu, Mangkok Sambal / Saus, Pisau / Alat Potong',
       'Baskom / Mangkok Besar, Nampan / Tray, Other',
       'Other, Pisau / Alat Potong',
       'Bangku / Kursi Kecil, Keranjang, Saringan / Strainer',
       'Other, Talenan', 'Other, Spatula, Tempat Nasi',
       'Aksesoris Pintu, Spatula', 'Cobek / Ulekan, Keranjang',
       'Baskom / Mangkok Besar, Mangkok Sambal / Saus, Other, Teko / Jug',
       'Aksesoris Pintu, Botol / Gelas / Mug, Gayung',
       'Peralatan Kamar Mandi, Rak / Rak Serbaguna',
       'Baskom / Mangkok Besar, Other, Tempat Nasi',
       'Keranjang, Other, Peralatan Makan, Pisau / Alat Potong, Plastik / Wadah Plastik, Spatula',
       'Celengan, Plastik / Wadah Plastik, Teko / Jug',
       'Botol / Gelas / Mug, Cobek / Ulekan, Mangkok Sambal / Saus, Other, Peralatan Makan, Plastik / Wadah Plastik, Tempat Nasi',
       'Aksesoris Mandi, Keranjang, Rak / Rak Serbaguna, Toples / Sealware',
       'Celengan, Tempat Sampah',
       'Botol / Gelas / Mug, Mangkok Sambal / Saus, Other, Peralatan Makan, Pisau / Alat Potong, Saringan / Strainer',
       'Baskom / Mangkok Besar, Keranjang, Mangkok Sambal / Saus, Peralatan Makan, Plastik / Wadah Plastik',
       'Mangkok Sambal / Saus, Peralatan Makan, Talenan',
       'Celengan, Nampan / Tray, Pisau / Alat Potong',
       'Keranjang, Perlengkapan Packing, Rak / Rak Serbaguna',
       'Peralatan Makan, Rak / Rak Serbaguna, Toples / Sealware',
       'Botol / Gelas / Mug, Mangkok Sambal / Saus, Other, Peralatan Makan, Piring',
       'Aksesoris Mandi, Celengan, Spatula, Toples / Sealware',
       'Celengan, Nampan / Tray',
       'Botol / Gelas / Mug, Mangkok, Peralatan Makan, Plastik / Wadah Plastik, Rak / Rak Serbaguna',
       'Celengan, Keranjang, Sapu / Pembersih Lantai, Sikat / Pembersih',
       'Celengan, Other, Toples / Sealware',
       'Mangkok Sambal / Saus, Peralatan Makan, Saringan / Strainer',
       'Baskom / Mangkok Besar, Mangkok, Nampan / Tray, Other, Rak / Rak Serbaguna, Saringan / Strainer, Tempat Nasi',
       'Baskom / Mangkok Besar, Celengan, Nampan / Tray',
       'Nampan / Tray, Saringan / Strainer, Spatula',
       'Celengan, Perlengkapan Packing, Plastik / Wadah Plastik',
       'Celengan, Saringan / Strainer, Sikat / Pembersih',
       'Other, Peralatan Makan',
       'Aksesoris Mandi, Botol / Gelas / Mug, Mangkok Sambal / Saus, Other, Peralatan Kamar Mandi',
       'Aksesoris Mandi, Celengan, Toples / Sealware',
       'Aksesoris ID Card, Aksesoris Pintu, Botol / Gelas / Mug, Peralatan Makan, Sapu / Pembersih Lantai',
       'Gayung, Nampan / Tray',
       'Celengan, Keranjang, Perlengkapan Packing',
       'Celengan, Toples / Sealware',
       'Baskom / Mangkok Besar, Celengan, Other, Sikat / Pembersih',
       'Aksesoris Mandi, Keranjang, Other, Perlengkapan Packing, Plastik / Wadah Plastik',
       'Keranjang, Piring', 'Aksesoris Pintu, Other, Peralatan Makan',
       'Aksesoris Pintu, Botol / Gelas / Mug, Nampan / Tray',
       'Baskom / Mangkok Besar, Keranjang, Other',
       'Nampan / Tray, Saringan / Strainer',
       'Botol / Gelas / Mug, Keranjang, Sikat / Pembersih',
       'Aksesoris Pintu, Mangkok, Peralatan Kamar Mandi',
       'Botol / Gelas / Mug, Celengan, Mangkok, Other, Pisau / Alat Potong',
       'Baskom / Mangkok Besar, Peralatan Makan, Rak / Rak Serbaguna, Tempat Nasi',
       'Mangkok Sambal / Saus, Other, Rak / Rak Serbaguna',
       'Aksesoris ID Card, Teko / Jug',
       'Other, Plastik / Wadah Plastik, Teko / Jug',
       'Keranjang, Peralatan Makan, Toples / Sealware',
       'Baskom / Mangkok Besar, Mangkok Sambal / Saus, Nampan / Tray, Other',
       'Aksesoris Pintu, Gantungan Baju / Hanger, Keranjang',
       'Keranjang, Plastik / Wadah Plastik',
       'Mangkok Sambal / Saus, Nampan / Tray, Sikat / Pembersih',
       'Baskom / Mangkok Besar, Other, Peralatan Makan',
       'Baskom / Mangkok Besar, Botol / Gelas / Mug, Other, Piring, Saringan / Strainer',
       'Aksesoris Pintu, Other, Talenan',
       'Aksesoris Pintu, Baskom / Mangkok Besar, Keranjang',
       'Baskom / Mangkok Besar, Plastik / Wadah Plastik, Talenan',
       'Cobek / Ulekan, Talenan',
       'Baskom / Mangkok Besar, Mangkok Sambal / Saus, Plastik / Wadah Plastik',
       'Botol / Gelas / Mug, Lunch Box / Rantang, Mangkok Sambal / Saus',
       'Baskom / Mangkok Besar, Celengan, Saringan / Strainer, Sikat / Pembersih',
       'Pengolah Bumbu / Sayur, Perlengkapan Packing',
       'Celengan, Pisau / Alat Potong',
       'Aksesoris ID Card, Other, Sapu / Pembersih Lantai, Teko / Jug',
       'Cobek / Ulekan, Gantungan Baju / Hanger, Other, Saringan / Strainer',
       'Bangku / Kursi Kecil, Celengan, Sapu / Pembersih Lantai',
       'Keranjang, Mangkok Sambal / Saus, Other, Peralatan Makan, Spatula, Toples / Sealware',
       'Aksesoris Pintu, Saringan / Strainer, Talenan',
       'Baskom / Mangkok Besar, Celengan, Other, Perlengkapan Packing',

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20848 entries, 0 to 20847
Data columns (total 19 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   order_id                            20848 non-null  object
 1   total_qty                           20848 non-null  int64
 2   total_weight_gr                     20848 non-null  int64
 3   total_returned_qty                  20848 non-null  int64
 4   Total Diskon                        20848 non-null  int64
 5   product_categories                  20848 non-null  object
 6   num_product_categories              20848 non-null  int64
 7   Status Pesanan                      20848 non-null  object
 8   Alasan Pembatalan                   2830 non-null   object
 9   Opsi Pengiriman                     20848 non-null  object
 10  Metode Pembayaran                   20848 non-null  object
 11  Kota/Kabupaten                      20848 non-null  object
 12  Provinsi                            20848 non-null  object
 13  Ongkos Kirim Dibayar oleh Pembeli   20848 non-null  int64
 14  Estimasi Potongan Biaya Pengiriman  20848 non-null  int64
 15  Total Pembayaran                    20848 non-null  int64
 16  Perkiraan Ongkos Kirim              20848 non-null  int64
 17  Waktu Pesanan Dibuat                18868 non-null  object
 18  source_file                         20848 non-null  object
dtypes: int64(9), object(10)
memory usage: 3.0+ MB

In [8]:
df_worker = pd.read_csv('ai_worker_burnout_attrition_2026.csv')

In [9]:
df_worker.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   employee_id                     1500 non-null   object
 1   job_role                        1500 non-null   object
 2   years_experience                1500 non-null   int64
 3   education_level                 1500 non-null   object
 4   country                         1500 non-null   object
 5   industry                        1500 non-null   object
 6   company_size                    1500 non-null   object
 7   remote_work_type                1500 non-null   object
 8   team_size                       1500 non-null   int64
 9   salary_usd_k                    1500 non-null   int64
 10  primary_ai_tool                 1500 non-null   object
 11  ai_tools_used_per_day           1500 non-null   int64
 12  hours_with_ai_assistance_daily  1500 non-null   float64
 13  ai_replaces_my_tasks_pct        1500 non-null   int64
 14  ai_adoption_stage               1500 non-null   object
 15  weekly_ai_upskilling_hrs        1500 non-null   float64
 16  productivity_score              1500 non-null   int64
 17  burnout_score                   1500 non-null   int64
 18  job_satisfaction_1_5            1500 non-null   float64
 19  fear_of_ai_replacement          1500 non-null   object
 20  attrition_risk                  1500 non-null   object
dtypes: float64(3), int64(7), object(11)
memory usage: 246.2+ KB

In [23]:
df_worker

,employee_id,job_role,years_experience,education_level,country,industry,company_size,remote_work_type,team_size,salary_usd_k,...,ai_tools_used_per_day,hours_with_ai_assistance_daily,ai_replaces_my_tasks_pct,ai_adoption_stage,weekly_ai_upskilling_hrs,productivity_score,burnout_score,job_satisfaction_1_5,fear_of_ai_replacement,attrition_risk
0,EMP0001,Data Analyst,7,PhD,India,Healthtech,Large (1000-5000),Fully Remote,8,184,...,1,0.6,37,Experimenting,4.9,59,58,3.0,Low,Medium
1,EMP0002,DevOps Engineer,3,Self-taught,Canada,Fintech,Large (1000-5000),Hybrid,42,51,...,3,0.6,78,Experimenting,6.6,64,47,3.6,Medium,Medium
2,EMP0003,Prompt Engineer,3,PhD,India,Automotive,Startup (<50),Hybrid,37,185,...,4,4.0,23,Optimizing,5.8,50,37,4.6,High,Medium
3,EMP0004,Backend Engineer,18,Master,Germany,Media,Mid (200-1000),Fully Remote,8,131,...,5,4.2,75,Integrating,1.4,77,67,3.0,Low,Medium
4,EMP0005,AI Researcher,5,Bachelor,India,E-commerce,Small (50-200),Fully Remote,21,99,...,7,0.7,61,Experimenting,1.6,58,54,3.6,Medium,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,EMP1496,Frontend Engineer,2,Master,Brazil,Fintech,Enterprise (5000+),Hybrid,36,47,...,7,6.9,69,Integrating,2.6,74,63,3.1,High,Medium
1496,EMP1497,Prompt Engineer,1,PhD,UK,E-commerce,Small (50-200),Hybrid,22,199,...,1,1.2,7,Integrating,6.9,39,25,3.5,Low,Low
1497,EMP1498,Backend Engineer,8,Bachelor,Canada,Cybersecurity,Mid (200-1000),Hybrid,48,120,...,3,6.8,73,Optimizing,4.0,44,65,2.9,High,High
1498,EMP1499,AI Ethics Officer,13,Self-taught,Netherlands,Media,Startup (<50),Fully Remote,41,208,...,6,3.2,68,Optimizing,4.1,77,53,2.8,Low,Medium
1499,EMP1500,Frontend Engineer,15,Self-taught,Australia,SaaS,Large (1000-5000),Hybrid,29,212,...,7,5.1,53,Integrating,2.8,50,51,3.5,Low,Medium

In [24]:
df_worker_attention_risk = df_worker[(df_worker['attrition_risk'] == 'High')]

In [30]:
df_worker['job_role'].value_counts()

job_role
Software Engineer    150
AI Researcher        135
Data Scientist       135
AI Ethics Officer    132
Cloud Architect      130
Backend Engineer     127
Product Manager      123
Data Analyst         122
Frontend Engineer    116
DevOps Engineer      116
ML Engineer          109
Prompt Engineer      105
Name: count, dtype: int64

In [33]:
df_worker_attention_risk[['burnout_score', 'job_satisfaction_1_5', 'years_experience', 'job_role', 'ai_adoption_stage']]

,burnout_score,job_satisfaction_1_5,years_experience,job_role,ai_adoption_stage
14,48,2.7,17,Backend Engineer,Integrating
17,50,2.6,17,Product Manager,Integrating
21,52,2.5,19,Cloud Architect,Experimenting
24,53,3.0,5,Cloud Architect,Experimenting
54,59,3.2,14,ML Engineer,Optimizing
...,...,...,...,...,...
1429,86,2.4,2,AI Researcher,Experimenting
1443,56,2.6,19,AI Researcher,AI-First
1460,68,1.9,17,DevOps Engineer,Experimenting
1470,73,2.3,4,Product Manager,AI-First
1497,65,2.9,8,Backend Engineer,Optimizing

In [34]:
df_logistic = pd.read_csv('smart_logistics_dataset.csv')

In [35]:
df_logistic

,Timestamp,Asset_ID,Latitude,Longitude,Inventory_Level,Shipment_Status,Temperature,Humidity,Traffic_Status,Waiting_Time,User_Transaction_Amount,User_Purchase_Frequency,Logistics_Delay_Reason,Asset_Utilization,Demand_Forecast,Logistics_Delay
0,2024-03-20 00:11:14,Truck_7,-65.7383,11.2497,390,Delayed,27.0,67.8,Detour,38,320,4,NaN,60.1,285,1
1,2024-10-30 07:53:51,Truck_6,22.2748,-131.7086,491,In Transit,22.5,54.3,Heavy,16,439,7,Weather,80.9,174,1
2,2024-07-29 18:42:48,Truck_10,54.9232,79.5455,190,In Transit,25.2,62.2,Detour,34,355,3,NaN,99.2,260,0
3,2024-10-28 00:50:54,Truck_9,42.3900,-1.4788,330,Delivered,25.4,52.3,Heavy,37,227,5,Traffic,97.4,160,1
4,2024-09-27 15:52:58,Truck_7,-65.8477,47.9468,480,Delayed,20.5,57.2,Clear,56,197,6,NaN,71.6,270,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2024-07-22 16:30:00,Truck_6,89.8701,73.6867,264,Delivered,26.9,70.0,Heavy,32,188,1,Weather,79.2,213,1
996,2024-04-30 04:58:58,Truck_5,-10.4792,-177.1239,479,Delivered,23.7,77.9,Detour,56,276,7,Weather,83.7,272,0
997,2024-10-27 22:09:13,Truck_2,-71.0609,75.3714,347,In Transit,21.0,63.1,Detour,35,382,5,NaN,74.8,275,0
998,2024-04-18 23:06:56,Truck_2,-76.7910,18.3631,276,Delivered,18.0,64.3,Heavy,10,361,5,NaN,88.6,242,1
999,2024-09-18 19:39:24,Truck_8,59.8356,-114.4198,157,Delayed,18.7,73.6,Clear,55,323,9,Mechanical Failure,81.3,141,1

In [36]:
df_bank = pd.read_csv('Banking_Fraud_Dataset.csv')
df_bank

,Transaction_ID,Customer_ID,Transaction_Amount,Transaction_Type,Transaction_Location,Transaction_Time,Device_Used,Account_Age,Credit_Score,Previous_Fraud,Is_Fraud
0,T1,C2539,8527.58,Deposit,"Hughesmouth, Mongolia",2025-01-20 03:17:34,Mobile,16,740,0,0
1,T2,C5318,9275.82,Deposit,"Huntville, Saint Pierre and Miquelon",2025-01-03 18:08:56,Web,5,848,0,1
2,T3,C8262,2202.49,Online Payment,"Patriciashire, Iceland",2025-01-24 05:54:01,ATM,2,616,1,1
3,T4,C3865,9352.32,Deposit,"Port Timothymouth, Palau",2025-01-19 01:15:30,ATM,9,437,1,0
4,T5,C7248,2081.75,Online Payment,"Lake Stevenfurt, Mauritius",2025-01-08 18:06:13,ATM,15,494,0,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,T9996,C2340,3678.03,Online Payment,"Port Matthew, Malawi",2025-01-14 05:47:08,Web,1,439,1,1
9996,T9997,C6185,6041.40,Transfer,"Lanceville, Swaziland",2025-01-08 04:40:34,POS Terminal,4,738,1,1
9997,T9998,C6114,4755.10,Online Payment,"North Scottmouth, Guinea-Bissau",2025-01-17 05:00:54,POS Terminal,18,649,1,1
9998,T9999,C4483,1649.96,Deposit,"North Miranda, Estonia",2025-01-23 09:44:47,POS Terminal,10,838,1,1
9999,T10000,C1171,6232.83,Deposit,"Gilesfort, Argentina",2025-01-08 03:30:27,Mobile,16,572,0,1

In [40]:
df_bank['Customer_ID'].value_counts()

Customer_ID
C9005    7
C7507    6
C4674    6
C1098    6
C8914    6
        ..
C3497    1
C9586    1
C4813    1
C9715    1
C2378    1
Name: count, Length: 5985, dtype: int64